apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-vnc-1
  labels:
    application: headless-vnc-1
spec:
  # 1 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      application: headless-vnc-1
  template:
    metadata:
      labels:
        application: headless-vnc-1
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: headless-vnc-1
        image: consol/rocky-xfce-vnc
        imagePullPolicy: Always
        args:
          ### make normal UI startup to connect via: oc rsh <pod-name> bash
          - '--tail-log'
        ### checks that vnc server is up and running
        livenessProbe:
          tcpSocket:
            port: 5901
          initialDelaySeconds: 1
          timeoutSeconds: 1
        ### checks if http-vnc connection is working
        readinessProbe:
          httpGet:
            path: /
            port: 6901
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 1
        #TODO remove later
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: headless-data
          mountPath: /volumedata
      volumes:
      - name: headless-data
        persistentVolumeClaim:
          claimName: headless-vnc-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headless-vnc-pvc
  labels:
    app: headless-vnc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: headless-vnc-1
  name: headless-vnc-1
spec:
  externalName: headless-vnc-1
  ports:
  - name: http-port-tcp
    protocol: TCP
    port: 6901
    targetPort: 6901
    nodePort: 32001
  - name: vnc-port-tcp
    protocol: TCP
    port: 5901
    targetPort: 5901
    nodePort: 32002
  selector:
    application: headless-vnc-1
  type: NodePort

